// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "stdafx.h"
#include "objects.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace eveobjects {

namespace {

const ::google::protobuf::Descriptor* infoObject_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  infoObject_reflection_ = NULL;
const ::google::protobuf::Descriptor* BooleanObject_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  BooleanObject_reflection_ = NULL;
const ::google::protobuf::Descriptor* functionCall_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  functionCall_reflection_ = NULL;
const ::google::protobuf::Descriptor* overview_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  overview_reflection_ = NULL;
const ::google::protobuf::Descriptor* label_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  label_reflection_ = NULL;
const ::google::protobuf::Descriptor* TargetList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TargetList_reflection_ = NULL;
const ::google::protobuf::Descriptor* targetentry_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  targetentry_reflection_ = NULL;
const ::google::protobuf::Descriptor* jammers_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  jammers_reflection_ = NULL;
const ::google::protobuf::Descriptor* Interface_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Interface_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_objects_2eproto() {
  protobuf_AddDesc_objects_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "objects.proto");
  GOOGLE_CHECK(file != NULL);
  infoObject_descriptor_ = file->message_type(0);
  static const int infoObject_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(infoObject, text_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(infoObject, value_),
  };
  infoObject_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      infoObject_descriptor_,
      infoObject::default_instance_,
      infoObject_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(infoObject, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(infoObject, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(infoObject));
  BooleanObject_descriptor_ = file->message_type(1);
  static const int BooleanObject_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BooleanObject, istrue_),
  };
  BooleanObject_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      BooleanObject_descriptor_,
      BooleanObject::default_instance_,
      BooleanObject_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BooleanObject, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BooleanObject, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(BooleanObject));
  functionCall_descriptor_ = file->message_type(2);
  static const int functionCall_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(functionCall, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(functionCall, strparameter_),
  };
  functionCall_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      functionCall_descriptor_,
      functionCall::default_instance_,
      functionCall_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(functionCall, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(functionCall, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(functionCall));
  overview_descriptor_ = file->message_type(3);
  static const int overview_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(overview, overviewentry_),
  };
  overview_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      overview_descriptor_,
      overview::default_instance_,
      overview_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(overview, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(overview, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(overview));
  label_descriptor_ = file->message_type(4);
  static const int label_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(label, text_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(label, topleftx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(label, toplefty_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(label, width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(label, height_),
  };
  label_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      label_descriptor_,
      label::default_instance_,
      label_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(label, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(label, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(label));
  TargetList_descriptor_ = file->message_type(5);
  static const int TargetList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetList, thistarget_),
  };
  TargetList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TargetList_descriptor_,
      TargetList::default_instance_,
      TargetList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TargetList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TargetList));
  targetentry_descriptor_ = file->message_type(6);
  static const int targetentry_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(targetentry, text_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(targetentry, jams_),
  };
  targetentry_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      targetentry_descriptor_,
      targetentry::default_instance_,
      targetentry_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(targetentry, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(targetentry, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(targetentry));
  jammers_descriptor_ = file->message_type(7);
  static const int jammers_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(jammers, jammer_),
  };
  jammers_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      jammers_descriptor_,
      jammers::default_instance_,
      jammers_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(jammers, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(jammers, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(jammers));
  Interface_descriptor_ = file->message_type(8);
  static const int Interface_offsets_[11] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, topleftx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, toplefty_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, height_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, hasclosebutton_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, closetopleftx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, closetoplefty_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, hascontinuebutton_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, continuetopleftx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, continuetoplefty_),
  };
  Interface_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Interface_descriptor_,
      Interface::default_instance_,
      Interface_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Interface, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Interface));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_objects_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    infoObject_descriptor_, &infoObject::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    BooleanObject_descriptor_, &BooleanObject::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    functionCall_descriptor_, &functionCall::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    overview_descriptor_, &overview::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    label_descriptor_, &label::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TargetList_descriptor_, &TargetList::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    targetentry_descriptor_, &targetentry::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    jammers_descriptor_, &jammers::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Interface_descriptor_, &Interface::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_objects_2eproto() {
  delete infoObject::default_instance_;
  delete infoObject_reflection_;
  delete BooleanObject::default_instance_;
  delete BooleanObject_reflection_;
  delete functionCall::default_instance_;
  delete functionCall_reflection_;
  delete overview::default_instance_;
  delete overview_reflection_;
  delete label::default_instance_;
  delete label_reflection_;
  delete TargetList::default_instance_;
  delete TargetList_reflection_;
  delete targetentry::default_instance_;
  delete targetentry_reflection_;
  delete jammers::default_instance_;
  delete jammers_reflection_;
  delete Interface::default_instance_;
  delete Interface_reflection_;
}

void protobuf_AddDesc_objects_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\robjects.proto\022\neveobjects\")\n\ninfoObjec"
    "t\022\014\n\004text\030\001 \001(\t\022\r\n\005value\030\002 \001(\005\"\037\n\rBoolea"
    "nObject\022\016\n\006istrue\030\001 \002(\010\"2\n\014functionCall\022"
    "\014\n\004name\030\001 \002(\t\022\024\n\014strparameter\030\002 \001(\t\"4\n\010o"
    "verview\022(\n\roverviewEntry\030\001 \003(\0132\021.eveobje"
    "cts.label\"X\n\005label\022\014\n\004text\030\001 \002(\t\022\020\n\010topL"
    "eftX\030\002 \002(\005\022\020\n\010topLeftY\030\003 \002(\005\022\r\n\005width\030\004 "
    "\002(\005\022\016\n\006height\030\005 \002(\005\"9\n\nTargetList\022+\n\nthi"
    "starget\030\001 \003(\0132\027.eveobjects.targetentry\"Q"
    "\n\013targetentry\022\037\n\004text\030\001 \001(\0132\021.eveobjects"
    ".label\022!\n\004jams\030\002 \001(\0132\023.eveobjects.jammer"
    "s\"\031\n\007jammers\022\016\n\006jammer\030\001 \003(\t\"\361\001\n\tInterfa"
    "ce\022\014\n\004name\030\001 \002(\t\022\020\n\010topleftX\030\002 \002(\005\022\020\n\010to"
    "pleftY\030\003 \002(\005\022\r\n\005width\030\004 \002(\005\022\016\n\006height\030\005 "
    "\002(\005\022\026\n\016hasCloseButton\030\006 \001(\010\022\025\n\rcloseTopL"
    "eftX\030\007 \001(\005\022\025\n\rcloseTopLeftY\030\010 \001(\005\022\031\n\021has"
    "ContinueButton\030\t \001(\010\022\030\n\020continueTopLeftX"
    "\030\n \001(\005\022\030\n\020continueTopLeftY\030\013 \001(\005", 712);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "objects.proto", &protobuf_RegisterTypes);
  infoObject::default_instance_ = new infoObject();
  BooleanObject::default_instance_ = new BooleanObject();
  functionCall::default_instance_ = new functionCall();
  overview::default_instance_ = new overview();
  label::default_instance_ = new label();
  TargetList::default_instance_ = new TargetList();
  targetentry::default_instance_ = new targetentry();
  jammers::default_instance_ = new jammers();
  Interface::default_instance_ = new Interface();
  infoObject::default_instance_->InitAsDefaultInstance();
  BooleanObject::default_instance_->InitAsDefaultInstance();
  functionCall::default_instance_->InitAsDefaultInstance();
  overview::default_instance_->InitAsDefaultInstance();
  label::default_instance_->InitAsDefaultInstance();
  TargetList::default_instance_->InitAsDefaultInstance();
  targetentry::default_instance_->InitAsDefaultInstance();
  jammers::default_instance_->InitAsDefaultInstance();
  Interface::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_objects_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_objects_2eproto {
  StaticDescriptorInitializer_objects_2eproto() {
    protobuf_AddDesc_objects_2eproto();
  }
} static_descriptor_initializer_objects_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int infoObject::kTextFieldNumber;
const int infoObject::kValueFieldNumber;
#endif  // !_MSC_VER

infoObject::infoObject()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void infoObject::InitAsDefaultInstance() {
}

infoObject::infoObject(const infoObject& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void infoObject::SharedCtor() {
  _cached_size_ = 0;
  text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  value_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

infoObject::~infoObject() {
  SharedDtor();
}

void infoObject::SharedDtor() {
  if (text_ != &::google::protobuf::internal::kEmptyString) {
    delete text_;
  }
  if (this != default_instance_) {
  }
}

void infoObject::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* infoObject::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return infoObject_descriptor_;
}

const infoObject& infoObject::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_objects_2eproto();  return *default_instance_;
}

infoObject* infoObject::default_instance_ = NULL;

infoObject* infoObject::New() const {
  return new infoObject;
}

void infoObject::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_text()) {
      if (text_ != &::google::protobuf::internal::kEmptyString) {
        text_->clear();
      }
    }
    value_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool infoObject::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string text = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_text()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->text().data(), this->text().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_value;
        break;
      }
      
      // optional int32 value = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_value:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &value_)));
          set_has_value();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void infoObject::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string text = 1;
  if (has_text()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->text().data(), this->text().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->text(), output);
  }
  
  // optional int32 value = 2;
  if (has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->value(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* infoObject::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string text = 1;
  if (has_text()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->text().data(), this->text().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->text(), target);
  }
  
  // optional int32 value = 2;
  if (has_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->value(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int infoObject::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string text = 1;
    if (has_text()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->text());
    }
    
    // optional int32 value = 2;
    if (has_value()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->value());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void infoObject::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const infoObject* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const infoObject*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void infoObject::MergeFrom(const infoObject& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_text()) {
      set_text(from.text());
    }
    if (from.has_value()) {
      set_value(from.value());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void infoObject::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void infoObject::CopyFrom(const infoObject& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool infoObject::IsInitialized() const {
  
  return true;
}

void infoObject::Swap(infoObject* other) {
  if (other != this) {
    std::swap(text_, other->text_);
    std::swap(value_, other->value_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata infoObject::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = infoObject_descriptor_;
  metadata.reflection = infoObject_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int BooleanObject::kIstrueFieldNumber;
#endif  // !_MSC_VER

BooleanObject::BooleanObject()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void BooleanObject::InitAsDefaultInstance() {
}

BooleanObject::BooleanObject(const BooleanObject& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void BooleanObject::SharedCtor() {
  _cached_size_ = 0;
  istrue_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

BooleanObject::~BooleanObject() {
  SharedDtor();
}

void BooleanObject::SharedDtor() {
  if (this != default_instance_) {
  }
}

void BooleanObject::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BooleanObject::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return BooleanObject_descriptor_;
}

const BooleanObject& BooleanObject::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_objects_2eproto();  return *default_instance_;
}

BooleanObject* BooleanObject::default_instance_ = NULL;

BooleanObject* BooleanObject::New() const {
  return new BooleanObject;
}

void BooleanObject::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    istrue_ = false;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool BooleanObject::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bool istrue = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &istrue_)));
          set_has_istrue();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void BooleanObject::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bool istrue = 1;
  if (has_istrue()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->istrue(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* BooleanObject::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bool istrue = 1;
  if (has_istrue()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->istrue(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int BooleanObject::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bool istrue = 1;
    if (has_istrue()) {
      total_size += 1 + 1;
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BooleanObject::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const BooleanObject* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const BooleanObject*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void BooleanObject::MergeFrom(const BooleanObject& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_istrue()) {
      set_istrue(from.istrue());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void BooleanObject::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BooleanObject::CopyFrom(const BooleanObject& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BooleanObject::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void BooleanObject::Swap(BooleanObject* other) {
  if (other != this) {
    std::swap(istrue_, other->istrue_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata BooleanObject::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = BooleanObject_descriptor_;
  metadata.reflection = BooleanObject_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int functionCall::kNameFieldNumber;
const int functionCall::kStrparameterFieldNumber;
#endif  // !_MSC_VER

functionCall::functionCall()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void functionCall::InitAsDefaultInstance() {
}

functionCall::functionCall(const functionCall& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void functionCall::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  strparameter_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

functionCall::~functionCall() {
  SharedDtor();
}

void functionCall::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (strparameter_ != &::google::protobuf::internal::kEmptyString) {
    delete strparameter_;
  }
  if (this != default_instance_) {
  }
}

void functionCall::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* functionCall::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return functionCall_descriptor_;
}

const functionCall& functionCall::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_objects_2eproto();  return *default_instance_;
}

functionCall* functionCall::default_instance_ = NULL;

functionCall* functionCall::New() const {
  return new functionCall;
}

void functionCall::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    if (has_strparameter()) {
      if (strparameter_ != &::google::protobuf::internal::kEmptyString) {
        strparameter_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool functionCall::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_strparameter;
        break;
      }
      
      // optional string strparameter = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_strparameter:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_strparameter()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->strparameter().data(), this->strparameter().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void functionCall::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }
  
  // optional string strparameter = 2;
  if (has_strparameter()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strparameter().data(), this->strparameter().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->strparameter(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* functionCall::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }
  
  // optional string strparameter = 2;
  if (has_strparameter()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->strparameter().data(), this->strparameter().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->strparameter(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int functionCall::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
    // optional string strparameter = 2;
    if (has_strparameter()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->strparameter());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void functionCall::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const functionCall* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const functionCall*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void functionCall::MergeFrom(const functionCall& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_strparameter()) {
      set_strparameter(from.strparameter());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void functionCall::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void functionCall::CopyFrom(const functionCall& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool functionCall::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  
  return true;
}

void functionCall::Swap(functionCall* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(strparameter_, other->strparameter_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata functionCall::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = functionCall_descriptor_;
  metadata.reflection = functionCall_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int overview::kOverviewEntryFieldNumber;
#endif  // !_MSC_VER

overview::overview()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void overview::InitAsDefaultInstance() {
}

overview::overview(const overview& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void overview::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

overview::~overview() {
  SharedDtor();
}

void overview::SharedDtor() {
  if (this != default_instance_) {
  }
}

void overview::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* overview::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return overview_descriptor_;
}

const overview& overview::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_objects_2eproto();  return *default_instance_;
}

overview* overview::default_instance_ = NULL;

overview* overview::New() const {
  return new overview;
}

void overview::Clear() {
  overviewentry_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool overview::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .eveobjects.label overviewEntry = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_overviewEntry:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_overviewentry()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_overviewEntry;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void overview::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .eveobjects.label overviewEntry = 1;
  for (int i = 0; i < this->overviewentry_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->overviewentry(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* overview::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .eveobjects.label overviewEntry = 1;
  for (int i = 0; i < this->overviewentry_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->overviewentry(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int overview::ByteSize() const {
  int total_size = 0;
  
  // repeated .eveobjects.label overviewEntry = 1;
  total_size += 1 * this->overviewentry_size();
  for (int i = 0; i < this->overviewentry_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->overviewentry(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void overview::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const overview* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const overview*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void overview::MergeFrom(const overview& from) {
  GOOGLE_CHECK_NE(&from, this);
  overviewentry_.MergeFrom(from.overviewentry_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void overview::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void overview::CopyFrom(const overview& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool overview::IsInitialized() const {
  
  for (int i = 0; i < overviewentry_size(); i++) {
    if (!this->overviewentry(i).IsInitialized()) return false;
  }
  return true;
}

void overview::Swap(overview* other) {
  if (other != this) {
    overviewentry_.Swap(&other->overviewentry_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata overview::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = overview_descriptor_;
  metadata.reflection = overview_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int label::kTextFieldNumber;
const int label::kTopLeftXFieldNumber;
const int label::kTopLeftYFieldNumber;
const int label::kWidthFieldNumber;
const int label::kHeightFieldNumber;
#endif  // !_MSC_VER

label::label()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void label::InitAsDefaultInstance() {
}

label::label(const label& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void label::SharedCtor() {
  _cached_size_ = 0;
  text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  topleftx_ = 0;
  toplefty_ = 0;
  width_ = 0;
  height_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

label::~label() {
  SharedDtor();
}

void label::SharedDtor() {
  if (text_ != &::google::protobuf::internal::kEmptyString) {
    delete text_;
  }
  if (this != default_instance_) {
  }
}

void label::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* label::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return label_descriptor_;
}

const label& label::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_objects_2eproto();  return *default_instance_;
}

label* label::default_instance_ = NULL;

label* label::New() const {
  return new label;
}

void label::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_text()) {
      if (text_ != &::google::protobuf::internal::kEmptyString) {
        text_->clear();
      }
    }
    topleftx_ = 0;
    toplefty_ = 0;
    width_ = 0;
    height_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool label::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string text = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_text()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->text().data(), this->text().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_topLeftX;
        break;
      }
      
      // required int32 topLeftX = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_topLeftX:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &topleftx_)));
          set_has_topleftx();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_topLeftY;
        break;
      }
      
      // required int32 topLeftY = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_topLeftY:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &toplefty_)));
          set_has_toplefty();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_width;
        break;
      }
      
      // required int32 width = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_width:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));
          set_has_width();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_height;
        break;
      }
      
      // required int32 height = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &height_)));
          set_has_height();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void label::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string text = 1;
  if (has_text()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->text().data(), this->text().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->text(), output);
  }
  
  // required int32 topLeftX = 2;
  if (has_topleftx()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->topleftx(), output);
  }
  
  // required int32 topLeftY = 3;
  if (has_toplefty()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->toplefty(), output);
  }
  
  // required int32 width = 4;
  if (has_width()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->width(), output);
  }
  
  // required int32 height = 5;
  if (has_height()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->height(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* label::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string text = 1;
  if (has_text()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->text().data(), this->text().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->text(), target);
  }
  
  // required int32 topLeftX = 2;
  if (has_topleftx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->topleftx(), target);
  }
  
  // required int32 topLeftY = 3;
  if (has_toplefty()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->toplefty(), target);
  }
  
  // required int32 width = 4;
  if (has_width()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->width(), target);
  }
  
  // required int32 height = 5;
  if (has_height()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->height(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int label::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string text = 1;
    if (has_text()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->text());
    }
    
    // required int32 topLeftX = 2;
    if (has_topleftx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->topleftx());
    }
    
    // required int32 topLeftY = 3;
    if (has_toplefty()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->toplefty());
    }
    
    // required int32 width = 4;
    if (has_width()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->width());
    }
    
    // required int32 height = 5;
    if (has_height()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->height());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void label::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const label* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const label*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void label::MergeFrom(const label& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_text()) {
      set_text(from.text());
    }
    if (from.has_topleftx()) {
      set_topleftx(from.topleftx());
    }
    if (from.has_toplefty()) {
      set_toplefty(from.toplefty());
    }
    if (from.has_width()) {
      set_width(from.width());
    }
    if (from.has_height()) {
      set_height(from.height());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void label::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void label::CopyFrom(const label& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool label::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;
  
  return true;
}

void label::Swap(label* other) {
  if (other != this) {
    std::swap(text_, other->text_);
    std::swap(topleftx_, other->topleftx_);
    std::swap(toplefty_, other->toplefty_);
    std::swap(width_, other->width_);
    std::swap(height_, other->height_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata label::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = label_descriptor_;
  metadata.reflection = label_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TargetList::kThistargetFieldNumber;
#endif  // !_MSC_VER

TargetList::TargetList()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void TargetList::InitAsDefaultInstance() {
}

TargetList::TargetList(const TargetList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void TargetList::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TargetList::~TargetList() {
  SharedDtor();
}

void TargetList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TargetList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TargetList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TargetList_descriptor_;
}

const TargetList& TargetList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_objects_2eproto();  return *default_instance_;
}

TargetList* TargetList::default_instance_ = NULL;

TargetList* TargetList::New() const {
  return new TargetList;
}

void TargetList::Clear() {
  thistarget_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TargetList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .eveobjects.targetentry thistarget = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_thistarget:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_thistarget()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_thistarget;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void TargetList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .eveobjects.targetentry thistarget = 1;
  for (int i = 0; i < this->thistarget_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->thistarget(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* TargetList::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated .eveobjects.targetentry thistarget = 1;
  for (int i = 0; i < this->thistarget_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->thistarget(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int TargetList::ByteSize() const {
  int total_size = 0;
  
  // repeated .eveobjects.targetentry thistarget = 1;
  total_size += 1 * this->thistarget_size();
  for (int i = 0; i < this->thistarget_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->thistarget(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TargetList::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TargetList* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TargetList*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TargetList::MergeFrom(const TargetList& from) {
  GOOGLE_CHECK_NE(&from, this);
  thistarget_.MergeFrom(from.thistarget_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TargetList::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TargetList::CopyFrom(const TargetList& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TargetList::IsInitialized() const {
  
  for (int i = 0; i < thistarget_size(); i++) {
    if (!this->thistarget(i).IsInitialized()) return false;
  }
  return true;
}

void TargetList::Swap(TargetList* other) {
  if (other != this) {
    thistarget_.Swap(&other->thistarget_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TargetList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TargetList_descriptor_;
  metadata.reflection = TargetList_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int targetentry::kTextFieldNumber;
const int targetentry::kJamsFieldNumber;
#endif  // !_MSC_VER

targetentry::targetentry()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void targetentry::InitAsDefaultInstance() {
  text_ = const_cast< ::eveobjects::label*>(&::eveobjects::label::default_instance());
  jams_ = const_cast< ::eveobjects::jammers*>(&::eveobjects::jammers::default_instance());
}

targetentry::targetentry(const targetentry& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void targetentry::SharedCtor() {
  _cached_size_ = 0;
  text_ = NULL;
  jams_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

targetentry::~targetentry() {
  SharedDtor();
}

void targetentry::SharedDtor() {
  if (this != default_instance_) {
    delete text_;
    delete jams_;
  }
}

void targetentry::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* targetentry::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return targetentry_descriptor_;
}

const targetentry& targetentry::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_objects_2eproto();  return *default_instance_;
}

targetentry* targetentry::default_instance_ = NULL;

targetentry* targetentry::New() const {
  return new targetentry;
}

void targetentry::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_text()) {
      if (text_ != NULL) text_->::eveobjects::label::Clear();
    }
    if (has_jams()) {
      if (jams_ != NULL) jams_->::eveobjects::jammers::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool targetentry::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .eveobjects.label text = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_text()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_jams;
        break;
      }
      
      // optional .eveobjects.jammers jams = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_jams:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_jams()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void targetentry::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional .eveobjects.label text = 1;
  if (has_text()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->text(), output);
  }
  
  // optional .eveobjects.jammers jams = 2;
  if (has_jams()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->jams(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* targetentry::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional .eveobjects.label text = 1;
  if (has_text()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->text(), target);
  }
  
  // optional .eveobjects.jammers jams = 2;
  if (has_jams()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->jams(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int targetentry::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional .eveobjects.label text = 1;
    if (has_text()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->text());
    }
    
    // optional .eveobjects.jammers jams = 2;
    if (has_jams()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->jams());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void targetentry::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const targetentry* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const targetentry*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void targetentry::MergeFrom(const targetentry& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_text()) {
      mutable_text()->::eveobjects::label::MergeFrom(from.text());
    }
    if (from.has_jams()) {
      mutable_jams()->::eveobjects::jammers::MergeFrom(from.jams());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void targetentry::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void targetentry::CopyFrom(const targetentry& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool targetentry::IsInitialized() const {
  
  if (has_text()) {
    if (!this->text().IsInitialized()) return false;
  }
  return true;
}

void targetentry::Swap(targetentry* other) {
  if (other != this) {
    std::swap(text_, other->text_);
    std::swap(jams_, other->jams_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata targetentry::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = targetentry_descriptor_;
  metadata.reflection = targetentry_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int jammers::kJammerFieldNumber;
#endif  // !_MSC_VER

jammers::jammers()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void jammers::InitAsDefaultInstance() {
}

jammers::jammers(const jammers& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void jammers::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

jammers::~jammers() {
  SharedDtor();
}

void jammers::SharedDtor() {
  if (this != default_instance_) {
  }
}

void jammers::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* jammers::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return jammers_descriptor_;
}

const jammers& jammers::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_objects_2eproto();  return *default_instance_;
}

jammers* jammers::default_instance_ = NULL;

jammers* jammers::New() const {
  return new jammers;
}

void jammers::Clear() {
  jammer_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool jammers::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string jammer = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_jammer:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_jammer()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->jammer(0).data(), this->jammer(0).length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_jammer;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void jammers::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated string jammer = 1;
  for (int i = 0; i < this->jammer_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8String(
    this->jammer(i).data(), this->jammer(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->jammer(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* jammers::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated string jammer = 1;
  for (int i = 0; i < this->jammer_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->jammer(i).data(), this->jammer(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->jammer(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int jammers::ByteSize() const {
  int total_size = 0;
  
  // repeated string jammer = 1;
  total_size += 1 * this->jammer_size();
  for (int i = 0; i < this->jammer_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->jammer(i));
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void jammers::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const jammers* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const jammers*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void jammers::MergeFrom(const jammers& from) {
  GOOGLE_CHECK_NE(&from, this);
  jammer_.MergeFrom(from.jammer_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void jammers::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void jammers::CopyFrom(const jammers& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool jammers::IsInitialized() const {
  
  return true;
}

void jammers::Swap(jammers* other) {
  if (other != this) {
    jammer_.Swap(&other->jammer_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata jammers::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = jammers_descriptor_;
  metadata.reflection = jammers_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int Interface::kNameFieldNumber;
const int Interface::kTopleftXFieldNumber;
const int Interface::kTopleftYFieldNumber;
const int Interface::kWidthFieldNumber;
const int Interface::kHeightFieldNumber;
const int Interface::kHasCloseButtonFieldNumber;
const int Interface::kCloseTopLeftXFieldNumber;
const int Interface::kCloseTopLeftYFieldNumber;
const int Interface::kHasContinueButtonFieldNumber;
const int Interface::kContinueTopLeftXFieldNumber;
const int Interface::kContinueTopLeftYFieldNumber;
#endif  // !_MSC_VER

Interface::Interface()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void Interface::InitAsDefaultInstance() {
}

Interface::Interface(const Interface& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void Interface::SharedCtor() {
  _cached_size_ = 0;
  name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  topleftx_ = 0;
  toplefty_ = 0;
  width_ = 0;
  height_ = 0;
  hasclosebutton_ = false;
  closetopleftx_ = 0;
  closetoplefty_ = 0;
  hascontinuebutton_ = false;
  continuetopleftx_ = 0;
  continuetoplefty_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Interface::~Interface() {
  SharedDtor();
}

void Interface::SharedDtor() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (this != default_instance_) {
  }
}

void Interface::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Interface::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Interface_descriptor_;
}

const Interface& Interface::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_objects_2eproto();  return *default_instance_;
}

Interface* Interface::default_instance_ = NULL;

Interface* Interface::New() const {
  return new Interface;
}

void Interface::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_name()) {
      if (name_ != &::google::protobuf::internal::kEmptyString) {
        name_->clear();
      }
    }
    topleftx_ = 0;
    toplefty_ = 0;
    width_ = 0;
    height_ = 0;
    hasclosebutton_ = false;
    closetopleftx_ = 0;
    closetoplefty_ = 0;
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    hascontinuebutton_ = false;
    continuetopleftx_ = 0;
    continuetoplefty_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Interface::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_topleftX;
        break;
      }
      
      // required int32 topleftX = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_topleftX:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &topleftx_)));
          set_has_topleftx();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_topleftY;
        break;
      }
      
      // required int32 topleftY = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_topleftY:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &toplefty_)));
          set_has_toplefty();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(32)) goto parse_width;
        break;
      }
      
      // required int32 width = 4;
      case 4: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_width:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));
          set_has_width();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(40)) goto parse_height;
        break;
      }
      
      // required int32 height = 5;
      case 5: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &height_)));
          set_has_height();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(48)) goto parse_hasCloseButton;
        break;
      }
      
      // optional bool hasCloseButton = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_hasCloseButton:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &hasclosebutton_)));
          set_has_hasclosebutton();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(56)) goto parse_closeTopLeftX;
        break;
      }
      
      // optional int32 closeTopLeftX = 7;
      case 7: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_closeTopLeftX:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &closetopleftx_)));
          set_has_closetopleftx();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(64)) goto parse_closeTopLeftY;
        break;
      }
      
      // optional int32 closeTopLeftY = 8;
      case 8: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_closeTopLeftY:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &closetoplefty_)));
          set_has_closetoplefty();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(72)) goto parse_hasContinueButton;
        break;
      }
      
      // optional bool hasContinueButton = 9;
      case 9: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_hasContinueButton:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &hascontinuebutton_)));
          set_has_hascontinuebutton();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_continueTopLeftX;
        break;
      }
      
      // optional int32 continueTopLeftX = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_continueTopLeftX:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &continuetopleftx_)));
          set_has_continuetopleftx();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(88)) goto parse_continueTopLeftY;
        break;
      }
      
      // optional int32 continueTopLeftY = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_continueTopLeftY:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &continuetoplefty_)));
          set_has_continuetoplefty();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void Interface::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(), output);
  }
  
  // required int32 topleftX = 2;
  if (has_topleftx()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->topleftx(), output);
  }
  
  // required int32 topleftY = 3;
  if (has_toplefty()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->toplefty(), output);
  }
  
  // required int32 width = 4;
  if (has_width()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->width(), output);
  }
  
  // required int32 height = 5;
  if (has_height()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->height(), output);
  }
  
  // optional bool hasCloseButton = 6;
  if (has_hasclosebutton()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->hasclosebutton(), output);
  }
  
  // optional int32 closeTopLeftX = 7;
  if (has_closetopleftx()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->closetopleftx(), output);
  }
  
  // optional int32 closeTopLeftY = 8;
  if (has_closetoplefty()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->closetoplefty(), output);
  }
  
  // optional bool hasContinueButton = 9;
  if (has_hascontinuebutton()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->hascontinuebutton(), output);
  }
  
  // optional int32 continueTopLeftX = 10;
  if (has_continuetopleftx()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(10, this->continuetopleftx(), output);
  }
  
  // optional int32 continueTopLeftY = 11;
  if (has_continuetoplefty()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(11, this->continuetoplefty(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* Interface::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string name = 1;
  if (has_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }
  
  // required int32 topleftX = 2;
  if (has_topleftx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->topleftx(), target);
  }
  
  // required int32 topleftY = 3;
  if (has_toplefty()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->toplefty(), target);
  }
  
  // required int32 width = 4;
  if (has_width()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->width(), target);
  }
  
  // required int32 height = 5;
  if (has_height()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->height(), target);
  }
  
  // optional bool hasCloseButton = 6;
  if (has_hasclosebutton()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(6, this->hasclosebutton(), target);
  }
  
  // optional int32 closeTopLeftX = 7;
  if (has_closetopleftx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->closetopleftx(), target);
  }
  
  // optional int32 closeTopLeftY = 8;
  if (has_closetoplefty()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->closetoplefty(), target);
  }
  
  // optional bool hasContinueButton = 9;
  if (has_hascontinuebutton()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(9, this->hascontinuebutton(), target);
  }
  
  // optional int32 continueTopLeftX = 10;
  if (has_continuetopleftx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(10, this->continuetopleftx(), target);
  }
  
  // optional int32 continueTopLeftY = 11;
  if (has_continuetoplefty()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(11, this->continuetoplefty(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int Interface::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }
    
    // required int32 topleftX = 2;
    if (has_topleftx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->topleftx());
    }
    
    // required int32 topleftY = 3;
    if (has_toplefty()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->toplefty());
    }
    
    // required int32 width = 4;
    if (has_width()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->width());
    }
    
    // required int32 height = 5;
    if (has_height()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->height());
    }
    
    // optional bool hasCloseButton = 6;
    if (has_hasclosebutton()) {
      total_size += 1 + 1;
    }
    
    // optional int32 closeTopLeftX = 7;
    if (has_closetopleftx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->closetopleftx());
    }
    
    // optional int32 closeTopLeftY = 8;
    if (has_closetoplefty()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->closetoplefty());
    }
    
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional bool hasContinueButton = 9;
    if (has_hascontinuebutton()) {
      total_size += 1 + 1;
    }
    
    // optional int32 continueTopLeftX = 10;
    if (has_continuetopleftx()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->continuetopleftx());
    }
    
    // optional int32 continueTopLeftY = 11;
    if (has_continuetoplefty()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->continuetoplefty());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Interface::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Interface* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Interface*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Interface::MergeFrom(const Interface& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_name()) {
      set_name(from.name());
    }
    if (from.has_topleftx()) {
      set_topleftx(from.topleftx());
    }
    if (from.has_toplefty()) {
      set_toplefty(from.toplefty());
    }
    if (from.has_width()) {
      set_width(from.width());
    }
    if (from.has_height()) {
      set_height(from.height());
    }
    if (from.has_hasclosebutton()) {
      set_hasclosebutton(from.hasclosebutton());
    }
    if (from.has_closetopleftx()) {
      set_closetopleftx(from.closetopleftx());
    }
    if (from.has_closetoplefty()) {
      set_closetoplefty(from.closetoplefty());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_hascontinuebutton()) {
      set_hascontinuebutton(from.hascontinuebutton());
    }
    if (from.has_continuetopleftx()) {
      set_continuetopleftx(from.continuetopleftx());
    }
    if (from.has_continuetoplefty()) {
      set_continuetoplefty(from.continuetoplefty());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Interface::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Interface::CopyFrom(const Interface& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Interface::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;
  
  return true;
}

void Interface::Swap(Interface* other) {
  if (other != this) {
    std::swap(name_, other->name_);
    std::swap(topleftx_, other->topleftx_);
    std::swap(toplefty_, other->toplefty_);
    std::swap(width_, other->width_);
    std::swap(height_, other->height_);
    std::swap(hasclosebutton_, other->hasclosebutton_);
    std::swap(closetopleftx_, other->closetopleftx_);
    std::swap(closetoplefty_, other->closetoplefty_);
    std::swap(hascontinuebutton_, other->hascontinuebutton_);
    std::swap(continuetopleftx_, other->continuetopleftx_);
    std::swap(continuetoplefty_, other->continuetoplefty_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Interface::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Interface_descriptor_;
  metadata.reflection = Interface_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace eveobjects

// @@protoc_insertion_point(global_scope)
